from fastapi import APIRouter
from app.api.api_v1.endpoints import agents, knowledge_bases, code_chat, prd_generator, library, flows, feedback, placeholders, optimize, integrations, pi_planning, ideation, opportunity_linker, webhooks, feasibility, business_case, settings, research_planner, journey_mapper, dashboard, experience_gap_analyzer, story_to_code, cx_recommender, release_prep, assistant, integrations_ado, integrations_servicenow, integrations_zendesk, integrations_qualtrics, roadmap_planner, scenario_modeler, roadmap_communicator, activity, goal_setting, okr_generator, kpi_assignment, measurement_framework, scope_definition, scope_monitor, competitive_analysis
from app.api.api_v1.endpoints.story_gen_endpoint import router as story_generator_router

api_router = APIRouter()
# Force reload for assistant updates
api_router.include_router(assistant.router, prefix="/assistant", tags=["assistant"])
api_router.include_router(integrations_ado.router, prefix="/integrations/ado", tags=["integrations-ado"])
api_router.include_router(integrations_servicenow.router, prefix="/integrations/servicenow", tags=["integrations-servicenow"])
api_router.include_router(integrations_zendesk.router, prefix="/integrations/zendesk", tags=["integrations-zendesk"])
api_router.include_router(integrations_qualtrics.router, prefix="/integrations/qualtrics", tags=["integrations-qualtrics"])
api_router.include_router(activity.router, prefix="/activity", tags=["activity"])
api_router.include_router(agents.router, prefix="/agents", tags=["agents"])
api_router.include_router(knowledge_bases.router, prefix="/knowledge-bases", tags=["knowledge-bases"])
api_router.include_router(story_generator_router, prefix="/story-generator", tags=["story-generator"])
api_router.include_router(story_to_code.router, prefix="/story-to-code", tags=["story-to-code"])
api_router.include_router(code_chat.router, prefix="/code-chat", tags=["code-chat"])
api_router.include_router(prd_generator.router, prefix="/prd-generator", tags=["prd-generator"])
api_router.include_router(library.router, prefix="/library", tags=["library"])
api_router.include_router(flows.router, prefix="/flows", tags=["flows"])
api_router.include_router(feedback.router, prefix="/feedback", tags=["feedback"])
api_router.include_router(optimize.router, prefix="/optimize", tags=["optimize"])
api_router.include_router(integrations.router, prefix="/integrations", tags=["integrations"])
api_router.include_router(pi_planning.router, prefix="/pi-planning", tags=["pi-planning"])
api_router.include_router(ideation.router, prefix="/ideation", tags=["ideation"])
api_router.include_router(opportunity_linker.router, prefix="/opportunity-linker", tags=["opportunity-linker"])
api_router.include_router(feasibility.router, prefix="/feasibility", tags=["feasibility"])
api_router.include_router(business_case.router, prefix="/business-case", tags=["business-case"])
api_router.include_router(research_planner.router, prefix="/cx/research-planner", tags=["research-planner"])
api_router.include_router(journey_mapper.router, prefix="/cx/journey-mapper", tags=["journey-mapper"])
api_router.include_router(experience_gap_analyzer.router, prefix="/cx/gap-analyzer", tags=["experience-gap-analyzer"])
api_router.include_router(cx_recommender.router, prefix="/cx/recommender", tags=["cx-recommender"])
api_router.include_router(webhooks.router, prefix="/webhooks", tags=["webhooks"])
api_router.include_router(settings.router, prefix="/settings", tags=["settings"])
api_router.include_router(dashboard.router, prefix="/dashboard", tags=["dashboard"])
api_router.include_router(release_prep.router, prefix="/release-prep", tags=["release-prep"])
api_router.include_router(roadmap_planner.router, prefix="/roadmap-planner", tags=["roadmap-planner"])
api_router.include_router(scenario_modeler.router, prefix="/scenario-modeler", tags=["scenario-modeler"])
api_router.include_router(roadmap_communicator.router, prefix="/roadmap-communicator", tags=["roadmap-communicator"])
# PM Workflow flows
api_router.include_router(goal_setting.router, prefix="/goal-setting", tags=["goal-setting"])
api_router.include_router(okr_generator.router, prefix="/okr-generator", tags=["okr-generator"])
api_router.include_router(kpi_assignment.router, prefix="/kpi-assignment", tags=["kpi-assignment"])
api_router.include_router(measurement_framework.router, prefix="/measurement-framework", tags=["measurement-framework"])
api_router.include_router(scope_definition.router, prefix="/scope-definition", tags=["scope-definition"])
api_router.include_router(scope_monitor.router, prefix="/scope-monitor", tags=["scope-monitor"])
api_router.include_router(competitive_analysis.router, prefix="/competitive-analysis", tags=["competitive-analysis"])
api_router.include_router(placeholders.router, prefix="", tags=["placeholders"])
