"""Initial migration

Revision ID: 0b1cb4eb912d
Revises: 
Create Date: 2025-12-05 17:59:51.359649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b1cb4eb912d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('holiday_configs')
    # op.drop_table('messages')
    # op.drop_index(op.f('pi_features_jira_key_idx'), table_name='pi_features')
    # op.drop_index(op.f('pi_features_priority_idx'), table_name='pi_features')
    # op.drop_index(op.f('pi_features_session_idx'), table_name='pi_features')
    # op.drop_table('pi_features')
    # op.drop_index(op.f('jira_boards_integration_idx'), table_name='jira_boards')
    # op.drop_index(op.f('jira_boards_unique'), table_name='jira_boards')
    # op.drop_table('jira_boards')
    # op.drop_index(op.f('pi_assignments_board_idx'), table_name='pi_feature_assignments')
    # op.drop_index(op.f('pi_assignments_feature_idx'), table_name='pi_feature_assignments')
    # op.drop_index(op.f('pi_assignments_session_idx'), table_name='pi_feature_assignments')
    # op.drop_index(op.f('pi_assignments_sprint_idx'), table_name='pi_feature_assignments')
    # op.drop_table('pi_feature_assignments')
    # op.drop_table('conversations')
    # op.drop_index(op.f('pi_sessions_integration_idx'), table_name='pi_planning_sessions')
    # op.drop_index(op.f('pi_sessions_status_idx'), table_name='pi_planning_sessions')
    # op.drop_table('pi_planning_sessions')
    # op.drop_index(op.f('pi_versions_created_idx'), table_name='pi_plan_versions')
    # op.drop_index(op.f('pi_versions_session_idx'), table_name='pi_plan_versions')
    # op.drop_table('pi_plan_versions')
    # op.drop_index(op.f('jira_sprints_board_idx'), table_name='jira_sprints')
    # op.drop_index(op.f('jira_sprints_integration_idx'), table_name='jira_sprints')
    # op.drop_index(op.f('jira_sprints_state_idx'), table_name='jira_sprints')
    # op.drop_index(op.f('jira_sprints_unique'), table_name='jira_sprints')
    # op.drop_table('jira_sprints')
    # op.drop_index(op.f('custom_holidays_config_idx'), table_name='custom_holidays')
    # op.drop_index(op.f('custom_holidays_date_idx'), table_name='custom_holidays')
    # op.drop_table('custom_holidays')
    # op.drop_index(op.f('pi_planned_items_board_idx'), table_name='pi_planned_items')
    # op.drop_index(op.f('pi_planned_items_session_idx'), table_name='pi_planned_items')
    # op.drop_index(op.f('pi_planned_items_sprint_idx'), table_name='pi_planned_items')
    # op.drop_table('pi_planned_items')
    # op.drop_index(op.f('field_mappings_integration_idx'), table_name='field_mappings')
    # op.drop_table('field_mappings')
    # op.drop_index(op.f('jira_issues_assignee_idx'), table_name='jira_issues')
    # op.drop_index(op.f('jira_issues_epic_idx'), table_name='jira_issues')
    # op.drop_index(op.f('jira_issues_integration_idx'), table_name='jira_issues')
    # op.drop_index(op.f('jira_issues_key_idx'), table_name='jira_issues')
    # op.drop_index(op.f('jira_issues_project_idx'), table_name='jira_issues')
    # op.drop_index(op.f('jira_issues_sprint_idx'), table_name='jira_issues')
    # op.drop_index(op.f('jira_issues_unique'), table_name='jira_issues')
    # op.drop_table('jira_issues')
    # op.drop_index(op.f('pi_sprints_session_idx'), table_name='pi_sprints')
    # op.drop_index(op.f('pi_sprints_unique'), table_name='pi_sprints')
    # op.drop_table('pi_sprints')
    # op.drop_index(op.f('pi_team_capabilities_board_idx'), table_name='pi_team_capabilities')
    # op.drop_table('pi_team_capabilities')
    # op.drop_index(op.f('required_fields_integration_idx'), table_name='required_fields')
    # op.drop_index(op.f('required_fields_project_idx'), table_name='required_fields')
    # op.drop_index(op.f('required_fields_unique'), table_name='required_fields')
    # op.drop_table('required_fields')
    # op.drop_index(op.f('pi_session_boards_session_idx'), table_name='pi_session_boards')
    # op.drop_table('pi_session_boards')
    # op.drop_index(op.f('extracted_facts_feedback_idx'), table_name='extracted_facts')
    # op.drop_index(op.f('extracted_facts_status_idx'), table_name='extracted_facts')
    # op.drop_table('extracted_facts')
    # op.drop_index(op.f('gen_extracted_facts_feedback_idx'), table_name='generation_extracted_facts')
    # op.drop_index(op.f('gen_extracted_facts_status_idx'), table_name='generation_extracted_facts')
    # op.drop_table('generation_extracted_facts')
    # op.drop_index(op.f('artifact_jira_links_artifact_idx'), table_name='artifact_jira_links')
    # op.drop_index(op.f('artifact_jira_links_integration_idx'), table_name='artifact_jira_links')
    # op.drop_table('artifact_jira_links')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifact_jira_links',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('artifact_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('artifact_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('integration_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('jira_issue_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('jira_issue_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('jira_project_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], name=op.f('artifact_jira_links_integration_id_integrations_id_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('artifact_jira_links_pkey'))
    )
    op.create_index(op.f('artifact_jira_links_integration_idx'), 'artifact_jira_links', ['integration_id'], unique=False)
    op.create_index(op.f('artifact_jira_links_artifact_idx'), 'artifact_jira_links', ['artifact_type', 'artifact_id'], unique=False)
    op.create_table('generation_extracted_facts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('feedback_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('knowledge_base_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['generation_feedback.id'], name=op.f('generation_extracted_facts_feedback_id_generation_feedback_id_f'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], name=op.f('generation_extracted_facts_knowledge_base_id_knowledge_bases_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('generation_extracted_facts_pkey'))
    )
    op.create_index(op.f('gen_extracted_facts_status_idx'), 'generation_extracted_facts', ['status'], unique=False)
    op.create_index(op.f('gen_extracted_facts_feedback_idx'), 'generation_extracted_facts', ['feedback_id'], unique=False)
    op.create_table('extracted_facts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('feedback_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('knowledge_base_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], name=op.f('extracted_facts_feedback_id_feedback_id_fk'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], name=op.f('extracted_facts_knowledge_base_id_knowledge_bases_id_fk'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('extracted_facts_pkey'))
    )
    op.create_index(op.f('extracted_facts_status_idx'), 'extracted_facts', ['status'], unique=False)
    op.create_index(op.f('extracted_facts_feedback_idx'), 'extracted_facts', ['feedback_id'], unique=False)
    op.create_table('pi_session_boards',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('pi_session_boards_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('board_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('board_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('velocity_override', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('capacity_adjustment', sa.INTEGER(), server_default=sa.text('100'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['pi_planning_sessions.id'], name='pi_session_boards_session_id_pi_planning_sessions_id_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pi_session_boards_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('pi_session_boards_session_idx'), 'pi_session_boards', ['session_id'], unique=False)
    op.create_table('required_fields',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('integration_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('project_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('issue_type_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('issue_type_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], name=op.f('required_fields_integration_id_integrations_id_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('required_fields_pkey'))
    )
    op.create_index(op.f('required_fields_unique'), 'required_fields', ['integration_id', 'project_id', 'issue_type_id'], unique=True)
    op.create_index(op.f('required_fields_project_idx'), 'required_fields', ['project_id'], unique=False)
    op.create_index(op.f('required_fields_integration_idx'), 'required_fields', ['integration_id'], unique=False)
    op.create_table('pi_team_capabilities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_board_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('can_work_on_all', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('allowed_feature_keys', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_board_id'], ['pi_session_boards.id'], name=op.f('pi_team_capabilities_session_board_id_pi_session_boards_id_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pi_team_capabilities_pkey'))
    )
    op.create_index(op.f('pi_team_capabilities_board_idx'), 'pi_team_capabilities', ['session_board_id'], unique=False)
    op.create_table('pi_sprints',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sprint_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('working_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('holidays', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('is_ip_sprint', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['pi_planning_sessions.id'], name=op.f('pi_sprints_session_id_pi_planning_sessions_id_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pi_sprints_pkey'))
    )
    op.create_index(op.f('pi_sprints_unique'), 'pi_sprints', ['session_id', 'sprint_number'], unique=True)
    op.create_index(op.f('pi_sprints_session_idx'), 'pi_sprints', ['session_id'], unique=False)
    op.create_table('jira_issues',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('integration_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('jira_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('issue_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('issue_type_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status_category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('assignee_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('assignee_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reporter_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reporter_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('story_points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sprint_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('epic_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('parent_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('project_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('resolution_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('synced_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], name=op.f('jira_issues_integration_id_integrations_id_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('jira_issues_pkey'))
    )
    op.create_index(op.f('jira_issues_unique'), 'jira_issues', ['integration_id', 'jira_id'], unique=True)
    op.create_index(op.f('jira_issues_sprint_idx'), 'jira_issues', ['sprint_id'], unique=False)
    op.create_index(op.f('jira_issues_project_idx'), 'jira_issues', ['project_key'], unique=False)
    op.create_index(op.f('jira_issues_key_idx'), 'jira_issues', ['key'], unique=False)
    op.create_index(op.f('jira_issues_integration_idx'), 'jira_issues', ['integration_id'], unique=False)
    op.create_index(op.f('jira_issues_epic_idx'), 'jira_issues', ['epic_key'], unique=False)
    op.create_index(op.f('jira_issues_assignee_idx'), 'jira_issues', ['assignee_id'], unique=False)
    op.create_table('field_mappings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('integration_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('our_field', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('provider_field_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('provider_field_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('provider_field_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('admin_confirmed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], name=op.f('field_mappings_integration_id_integrations_id_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('field_mappings_pkey'))
    )
    op.create_index(op.f('field_mappings_integration_idx'), 'field_mappings', ['integration_id'], unique=False)
    op.create_table('pi_planned_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('jira_issue_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('jira_issue_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('assigned_board_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('target_sprint_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sequence_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estimated_points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dependencies', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_suggested', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['pi_planning_sessions.id'], name=op.f('pi_planned_items_session_id_pi_planning_sessions_id_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pi_planned_items_pkey'))
    )
    op.create_index(op.f('pi_planned_items_sprint_idx'), 'pi_planned_items', ['target_sprint_id'], unique=False)
    op.create_index(op.f('pi_planned_items_session_idx'), 'pi_planned_items', ['session_id'], unique=False)
    op.create_index(op.f('pi_planned_items_board_idx'), 'pi_planned_items', ['assigned_board_id'], unique=False)
    op.create_table('custom_holidays',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('config_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('holiday_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_recurring', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['holiday_configs.id'], name=op.f('custom_holidays_config_id_holiday_configs_id_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('custom_holidays_pkey'))
    )
    op.create_index(op.f('custom_holidays_date_idx'), 'custom_holidays', ['holiday_date'], unique=False)
    op.create_index(op.f('custom_holidays_config_idx'), 'custom_holidays', ['config_id'], unique=False)
    op.create_table('jira_sprints',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('integration_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('board_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('jira_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('state', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('committed_points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goal', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('synced_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], name=op.f('jira_sprints_integration_id_integrations_id_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('jira_sprints_pkey'))
    )
    op.create_index(op.f('jira_sprints_unique'), 'jira_sprints', ['integration_id', 'jira_id'], unique=True)
    op.create_index(op.f('jira_sprints_state_idx'), 'jira_sprints', ['state'], unique=False)
    op.create_index(op.f('jira_sprints_integration_idx'), 'jira_sprints', ['integration_id'], unique=False)
    op.create_index(op.f('jira_sprints_board_idx'), 'jira_sprints', ['board_id'], unique=False)
    op.create_table('pi_plan_versions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version_number', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('pi_plan_versions_created_by_users_id_fk')),
    sa.ForeignKeyConstraint(['session_id'], ['pi_planning_sessions.id'], name=op.f('pi_plan_versions_session_id_pi_planning_sessions_id_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pi_plan_versions_pkey'))
    )
    op.create_index(op.f('pi_versions_session_idx'), 'pi_plan_versions', ['session_id'], unique=False)
    op.create_index(op.f('pi_versions_created_idx'), 'pi_plan_versions', ['created_at'], unique=False)
    op.create_table('pi_planning_sessions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('pi_planning_sessions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('integration_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('sprint_count', sa.INTEGER(), server_default=sa.text('5'), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'draft'::text"), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('sprint_length_weeks', sa.INTEGER(), server_default=sa.text('2'), autoincrement=False, nullable=True),
    sa.Column('plannable_issue_type', sa.TEXT(), server_default=sa.text("'epic'::text"), autoincrement=False, nullable=True),
    sa.Column('custom_issue_type_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('holiday_config_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('include_ip_sprint', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('current_version', sa.TEXT(), server_default=sa.text("'1.0'::text"), autoincrement=False, nullable=True),
    sa.Column('project_keys', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='pi_planning_sessions_created_by_users_id_fk'),
    sa.ForeignKeyConstraint(['holiday_config_id'], ['holiday_configs.id'], name='pi_planning_sessions_holiday_config_id_holiday_configs_id_fk'),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], name='pi_planning_sessions_integration_id_integrations_id_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pi_planning_sessions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('pi_sessions_status_idx'), 'pi_planning_sessions', ['status'], unique=False)
    op.create_index(op.f('pi_sessions_integration_idx'), 'pi_planning_sessions', ['integration_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('conversations_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name='conversations_agent_id_agents_id_fk'),
    sa.PrimaryKeyConstraint('id', name='conversations_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('pi_feature_assignments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('feature_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('board_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_sprint_num', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('end_sprint_num', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('allocated_points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sequence_in_sprint', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('ai_rationale', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('manual_override', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('override_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['pi_features.id'], name=op.f('pi_feature_assignments_feature_id_pi_features_id_fk'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['pi_planning_sessions.id'], name=op.f('pi_feature_assignments_session_id_pi_planning_sessions_id_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pi_feature_assignments_pkey'))
    )
    op.create_index(op.f('pi_assignments_sprint_idx'), 'pi_feature_assignments', ['start_sprint_num'], unique=False)
    op.create_index(op.f('pi_assignments_session_idx'), 'pi_feature_assignments', ['session_id'], unique=False)
    op.create_index(op.f('pi_assignments_feature_idx'), 'pi_feature_assignments', ['feature_id'], unique=False)
    op.create_index(op.f('pi_assignments_board_idx'), 'pi_feature_assignments', ['board_id'], unique=False)
    op.create_table('jira_boards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('integration_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('jira_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('project_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('velocity_avg', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('velocity_last_n', sa.INTEGER(), server_default=sa.text('5'), autoincrement=False, nullable=True),
    sa.Column('synced_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], name=op.f('jira_boards_integration_id_integrations_id_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('jira_boards_pkey'))
    )
    op.create_index(op.f('jira_boards_unique'), 'jira_boards', ['integration_id', 'jira_id'], unique=True)
    op.create_index(op.f('jira_boards_integration_idx'), 'jira_boards', ['integration_id'], unique=False)
    op.create_table('pi_features',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('jira_issue_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('jira_issue_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('issue_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('priority_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estimated_sprints', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('dependencies', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('project_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('imported_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['pi_planning_sessions.id'], name=op.f('pi_features_session_id_pi_planning_sessions_id_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pi_features_pkey'))
    )
    op.create_index(op.f('pi_features_session_idx'), 'pi_features', ['session_id'], unique=False)
    op.create_index(op.f('pi_features_priority_idx'), 'pi_features', ['priority_order'], unique=False)
    op.create_index(op.f('pi_features_jira_key_idx'), 'pi_features', ['jira_issue_key'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('tool_call_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('messages_conversation_id_conversations_id_fk')),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    op.create_table('holiday_configs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('calendar_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('country_codes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('is_default', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('holiday_configs_pkey'))
    )
    # ### end Alembic commands ###
