"""add_roadmap_planner_tables

Revision ID: 32cec55b3b82
Revises: aa51539b785e
Create Date: 2025-12-29 12:13:00.252012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32cec55b3b82'
down_revision: Union[str, Sequence[str], None] = 'aa51539b785e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jira_field_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('roadmap_field', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('jira_field_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('jira_field_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_custom_field', sa.Boolean(), nullable=False),
    sa.Column('value_mappings', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roadmap_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('story_artifact_ids', sa.JSON(), nullable=True),
    sa.Column('sprint_length_weeks', sa.Integer(), nullable=False),
    sa.Column('team_velocity', sa.Integer(), nullable=False),
    sa.Column('buffer_percentage', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('progress_step', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('progress_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('total_sprints', sa.Integer(), nullable=False),
    sa.Column('total_themes', sa.Integer(), nullable=False),
    sa.Column('total_milestones', sa.Integer(), nullable=False),
    sa.Column('total_dependencies', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roadmap_themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('business_objective', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('success_metrics', sa.JSON(), nullable=True),
    sa.Column('total_effort_points', sa.Integer(), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('jira_epic_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('jira_synced_at', sa.DateTime(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['roadmap_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roadmap_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('source_artifact_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('item_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('effort_points', sa.Integer(), nullable=False),
    sa.Column('risk_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value_score', sa.Integer(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('assigned_sprint', sa.Integer(), nullable=True),
    sa.Column('sprint_position', sa.Integer(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('jira_issue_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('jira_synced_at', sa.DateTime(), nullable=True),
    sa.Column('is_manually_positioned', sa.Boolean(), nullable=False),
    sa.Column('is_excluded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['roadmap_sessions.id'], ),
    sa.ForeignKeyConstraint(['source_artifact_id'], ['generated_artifacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roadmap_milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_sprint', sa.Integer(), nullable=True),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.Column('theme_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=True),
    sa.Column('completion_percentage', sa.Integer(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['roadmap_sessions.id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['roadmap_themes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roadmap_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('from_item_id', sa.Integer(), nullable=False),
    sa.Column('to_item_id', sa.Integer(), nullable=False),
    sa.Column('dependency_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rationale', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('jira_link_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('jira_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_item_id'], ['roadmap_items.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['roadmap_sessions.id'], ),
    sa.ForeignKeyConstraint(['to_item_id'], ['roadmap_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jira_sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('theme_id', sa.Integer(), nullable=True),
    sa.Column('dependency_id', sa.Integer(), nullable=True),
    sa.Column('sync_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('jira_issue_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('jira_link_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sync_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('response_data', sa.JSON(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dependency_id'], ['roadmap_dependencies.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['roadmap_items.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['roadmap_sessions.id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['roadmap_themes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('jira_sync_logs')
    op.drop_table('roadmap_dependencies')
    op.drop_table('roadmap_milestones')
    op.drop_table('roadmap_items')
    op.drop_table('roadmap_themes')
    op.drop_table('roadmap_sessions')
    op.drop_table('jira_field_mappings')
