"""add_missing_columns

Revision ID: 580365840fe0
Revises: c13ede22f09e
Create Date: 2025-12-26 10:58:07.493185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '580365840fe0'
down_revision: Union[str, Sequence[str], None] = 'c13ede22f09e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_prds', sa.Column('progress_step', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('generated_prds', sa.Column('progress_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('generated_prds', sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_prds', 'error_message')
    op.drop_column('generated_prds', 'progress_message')
    op.drop_column('generated_prds', 'progress_step')
    # ### end Alembic commands ###
