"""Add feasibility analyzer tables

Revision ID: 5ccc1264e0ec
Revises: 0e9c4a51f89b
Create Date: 2025-12-24 07:09:01.247792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ccc1264e0ec'
down_revision: Union[str, Sequence[str], None] = '0e9c4a51f89b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feasibility_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('feature_description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('technical_constraints', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_users', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('auto_detected_stack', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('progress_step', sa.Integer(), nullable=False),
    sa.Column('progress_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('go_no_go_recommendation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('executive_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('generation_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('risk_category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('risk_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('impact', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('mitigation_strategy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['feasibility_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('proficiency_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estimated_person_weeks', sa.Float(), nullable=False),
    sa.Column('is_gap', sa.Boolean(), nullable=False),
    sa.Column('gap_mitigation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['feasibility_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technical_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('component_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('component_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('technical_category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('optimistic_hours', sa.Float(), nullable=False),
    sa.Column('realistic_hours', sa.Float(), nullable=False),
    sa.Column('pessimistic_hours', sa.Float(), nullable=False),
    sa.Column('confidence_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estimated_by_agent', sa.Boolean(), nullable=False),
    sa.Column('is_editable', sa.Boolean(), nullable=False),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('can_parallelize', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['feasibility_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeline_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('scenario_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_weeks', sa.Float(), nullable=False),
    sa.Column('sprint_count', sa.Integer(), nullable=False),
    sa.Column('parallelization_factor', sa.Float(), nullable=False),
    sa.Column('overhead_percentage', sa.Float(), nullable=False),
    sa.Column('team_size_assumed', sa.Integer(), nullable=False),
    sa.Column('confidence_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rationale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['feasibility_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actual_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('actual_hours_spent', sa.Float(), nullable=False),
    sa.Column('actual_completion_date', sa.DateTime(), nullable=False),
    sa.Column('variance_percentage', sa.Float(), nullable=False),
    sa.Column('lessons_learned', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['technical_components.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['feasibility_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_prioritization_sessions_ideation_session_id'), table_name='prioritization_sessions')
    op.drop_index(op.f('ix_prioritization_sessions_user_id'), table_name='prioritization_sessions')
    op.drop_table('prioritization_sessions')
    op.drop_index(op.f('ix_prioritized_ideas_generated_idea_id'), table_name='prioritized_ideas')
    op.drop_index(op.f('ix_prioritized_ideas_prioritization_session_id'), table_name='prioritized_ideas')
    op.drop_table('prioritized_ideas')
    op.drop_index(op.f('ix_user_goals_session_id'), table_name='user_goals')
    op.drop_index(op.f('ix_user_goals_user_id'), table_name='user_goals')
    op.drop_table('user_goals')
    op.drop_index(op.f('ix_goal_sessions_user_id'), table_name='goal_sessions')
    op.drop_table('goal_sessions')
    op.alter_column('generated_ideas', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('generated_ideas', 'effort_estimate',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('generated_ideas', 'impact_estimate',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('generated_ideas', 'impact_rationale',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('generated_ideas', 'feasibility_rationale',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('generated_ideas', 'effort_rationale',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('generated_ideas', 'strategic_fit_rationale',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('generated_ideas', 'risk_rationale',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('generated_ideas', 'is_duplicate',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('generated_ideas', 'is_final',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('generated_ideas', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('generated_ideas', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('generated_ideas', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('generated_ideas_session_id_fkey'), 'generated_ideas', type_='foreignkey')
    op.create_foreign_key(None, 'generated_ideas', 'ideation_sessions', ['session_id'], ['id'])
    op.alter_column('idea_clusters', 'theme_description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('idea_clusters', 'idea_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('idea_clusters', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('idea_clusters_session_id_fkey'), 'idea_clusters', type_='foreignkey')
    op.create_foreign_key(None, 'idea_clusters', 'ideation_sessions', ['session_id'], ['id'])
    op.alter_column('ideation_sessions', 'problem_statement',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('ideation_sessions', 'constraints',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('ideation_sessions', 'goals',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('ideation_sessions', 'research_insights',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('ideation_sessions', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('ideation_sessions', 'progress_step',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('ideation_sessions', 'progress_message',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('ideation_sessions', 'error_message',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('ideation_sessions', 'confidence',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('ideation_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ideation_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_ideation_sessions_prioritization_session_id'), 'ideation_sessions', ['prioritization_session_id'], unique=False)
    op.create_foreign_key(None, 'ideation_sessions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ideation_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_ideation_sessions_prioritization_session_id'), table_name='ideation_sessions')
    op.alter_column('ideation_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ideation_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ideation_sessions', 'confidence',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('ideation_sessions', 'error_message',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ideation_sessions', 'progress_message',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ideation_sessions', 'progress_step',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('ideation_sessions', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('ideation_sessions', 'research_insights',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ideation_sessions', 'goals',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ideation_sessions', 'constraints',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ideation_sessions', 'problem_statement',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'idea_clusters', type_='foreignkey')
    op.create_foreign_key(op.f('idea_clusters_session_id_fkey'), 'idea_clusters', 'ideation_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.alter_column('idea_clusters', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('idea_clusters', 'idea_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('idea_clusters', 'theme_description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'generated_ideas', type_='foreignkey')
    op.create_foreign_key(op.f('generated_ideas_session_id_fkey'), 'generated_ideas', 'ideation_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.alter_column('generated_ideas', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('generated_ideas', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('generated_ideas', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('generated_ideas', 'is_final',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('generated_ideas', 'is_duplicate',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('generated_ideas', 'risk_rationale',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('generated_ideas', 'strategic_fit_rationale',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('generated_ideas', 'effort_rationale',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('generated_ideas', 'feasibility_rationale',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('generated_ideas', 'impact_rationale',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('generated_ideas', 'impact_estimate',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('generated_ideas', 'effort_estimate',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('generated_ideas', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_table('goal_sessions',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_goals', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('team_charter', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('job_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role_responsibilities', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('generation_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('goal_sessions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='goal_sessions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='goal_sessions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_goal_sessions_user_id'), 'goal_sessions', ['user_id'], unique=False)
    op.create_table('user_goals',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('specific', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('measurable', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('achievable', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('relevant', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('time_bound', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('progress_notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('completion_percentage', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['goal_sessions.id'], name=op.f('user_goals_session_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_goals_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_goals_pkey'))
    )
    op.create_index(op.f('ix_user_goals_user_id'), 'user_goals', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_goals_session_id'), 'user_goals', ['session_id'], unique=False)
    op.create_table('prioritized_ideas',
    sa.Column('prioritization_session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generated_idea_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('market_opportunity', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('strategic_opportunity', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('customer_opportunity', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('strategic_fit_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('strategic_fit_rationale', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tshirt_size', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('size_rationale', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('size_confidence', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('potential_revenue', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('priority_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('priority_tier', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['generated_idea_id'], ['generated_ideas.id'], name=op.f('prioritized_ideas_generated_idea_id_fkey')),
    sa.ForeignKeyConstraint(['prioritization_session_id'], ['prioritization_sessions.id'], name=op.f('prioritized_ideas_prioritization_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('prioritized_ideas_pkey'))
    )
    op.create_index(op.f('ix_prioritized_ideas_prioritization_session_id'), 'prioritized_ideas', ['prioritization_session_id'], unique=False)
    op.create_index(op.f('ix_prioritized_ideas_generated_idea_id'), 'prioritized_ideas', ['generated_idea_id'], unique=False)
    op.create_table('prioritization_sessions',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ideation_session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('progress_step', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('progress_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('portfolio_summary', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('processing_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ideation_session_id'], ['ideation_sessions.id'], name=op.f('prioritization_sessions_ideation_session_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('prioritization_sessions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('prioritization_sessions_pkey'))
    )
    op.create_index(op.f('ix_prioritization_sessions_user_id'), 'prioritization_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_prioritization_sessions_ideation_session_id'), 'prioritization_sessions', ['ideation_session_id'], unique=False)
    op.drop_table('actual_results')
    op.drop_table('timeline_scenarios')
    op.drop_table('technical_components')
    op.drop_table('skill_requirements')
    op.drop_table('risk_assessments')
    op.drop_table('feasibility_sessions')
    # ### end Alembic commands ###
