"""Add research planner tables

Revision ID: 707ed95e254d
Revises: 3b10004ec8ee
Create Date: 2025-12-26 06:32:18.657818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '707ed95e254d'
down_revision: Union[str, Sequence[str], None] = '3b10004ec8ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_plan_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('objective', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('progress_step', sa.Integer(), nullable=False),
    sa.Column('progress_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('selected_methods', sa.JSON(), nullable=True),
    sa.Column('suggested_sequence', sa.JSON(), nullable=True),
    sa.Column('generation_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_guides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('participant_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('focus_areas', sa.JSON(), nullable=True),
    sa.Column('content_markdown', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=True),
    sa.Column('user_edited_content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['research_plan_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommended_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('method_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('method_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rationale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('effort', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cost_estimate', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timeline', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('participant_count', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['research_plan_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recruiting_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('participant_criteria', sa.JSON(), nullable=True),
    sa.Column('participant_count', sa.Integer(), nullable=False),
    sa.Column('segmentation', sa.JSON(), nullable=True),
    sa.Column('detailed_criteria', sa.JSON(), nullable=True),
    sa.Column('screener_questions', sa.JSON(), nullable=True),
    sa.Column('recruiting_sources', sa.JSON(), nullable=True),
    sa.Column('email_templates', sa.JSON(), nullable=True),
    sa.Column('incentive_recommendation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expected_response_rate', sa.Float(), nullable=False),
    sa.Column('contacts_needed', sa.Integer(), nullable=False),
    sa.Column('timeline_estimate', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['research_plan_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('target_audience', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('survey_length', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question_types', sa.JSON(), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=True),
    sa.Column('analysis_plan', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estimated_completion_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['research_plan_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: Not dropping old tables (user_goals, goal_sessions, prioritization_sessions, prioritized_ideas)
    # to preserve any existing data. These can be cleaned up in a separate migration if needed.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prioritized_ideas',
    sa.Column('prioritization_session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generated_idea_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('market_opportunity', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('strategic_opportunity', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('customer_opportunity', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('strategic_fit_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('strategic_fit_rationale', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tshirt_size', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('size_rationale', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('size_confidence', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('potential_revenue', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('priority_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('priority_tier', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['generated_idea_id'], ['generated_ideas.id'], name=op.f('prioritized_ideas_generated_idea_id_fkey')),
    sa.ForeignKeyConstraint(['prioritization_session_id'], ['prioritization_sessions.id'], name=op.f('prioritized_ideas_prioritization_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('prioritized_ideas_pkey'))
    )
    op.create_index(op.f('ix_prioritized_ideas_prioritization_session_id'), 'prioritized_ideas', ['prioritization_session_id'], unique=False)
    op.create_index(op.f('ix_prioritized_ideas_generated_idea_id'), 'prioritized_ideas', ['generated_idea_id'], unique=False)
    op.create_table('prioritization_sessions',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ideation_session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('progress_step', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('progress_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('portfolio_summary', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('processing_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ideation_session_id'], ['ideation_sessions.id'], name=op.f('prioritization_sessions_ideation_session_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('prioritization_sessions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('prioritization_sessions_pkey'))
    )
    op.create_index(op.f('ix_prioritization_sessions_user_id'), 'prioritization_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_prioritization_sessions_ideation_session_id'), 'prioritization_sessions', ['ideation_session_id'], unique=False)
    op.create_table('goal_sessions',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_goals', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('team_charter', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('job_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role_responsibilities', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('generation_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('goal_sessions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='goal_sessions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='goal_sessions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_goal_sessions_user_id'), 'goal_sessions', ['user_id'], unique=False)
    op.create_table('user_goals',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('specific', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('measurable', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('achievable', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('relevant', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('time_bound', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('progress_notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('completion_percentage', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['goal_sessions.id'], name=op.f('user_goals_session_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_goals_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_goals_pkey'))
    )
    op.create_index(op.f('ix_user_goals_user_id'), 'user_goals', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_goals_session_id'), 'user_goals', ['session_id'], unique=False)
    op.drop_table('surveys')
    op.drop_table('recruiting_plans')
    op.drop_table('recommended_methods')
    op.drop_table('interview_guides')
    op.drop_table('research_plan_sessions')
    # ### end Alembic commands ###
