"""
Goal Setting Models

Database models for the Goal Setting Assistant workflow.
"""
from datetime import datetime
from typing import Optional, List, Dict, Any
from sqlmodel import Field, SQLModel, JSON, Column
from humps import camelize


def to_camel(string):
    return camelize(string)


class GoalSettingSession(SQLModel, table=True):
    """Main session for goal setting workflow"""
    __tablename__ = "goal_setting_sessions"

    class Config:
        alias_generator = to_camel
        populate_by_name = True

    id: Optional[int] = Field(default=None, primary_key=True)
    user_id: Optional[int] = Field(default=None, foreign_key="users.id")

    # Input fields (matching original prototype)
    domain: str  # PM Role / Domain (e.g., "Onboarding + Authentication")
    strategy: str  # Company Strategy
    team_charter: Optional[str] = None  # Team Charter
    problem_statements: Optional[str] = None  # Customer Problem Statements
    baselines: Optional[str] = None  # Product-Specific Responsibilities (Baselines)

    # Processing state
    status: str = Field(default="pending")  # pending, generating, completed, failed
    progress_message: Optional[str] = None
    error_message: Optional[str] = None

    # Output summary
    executive_summary: Optional[str] = None

    # Metadata
    generation_metadata: Optional[Dict[str, Any]] = Field(default=None, sa_column=Column(JSON))
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    completed_at: Optional[datetime] = None


class Goal(SQLModel, table=True):
    """Individual goal generated by the AI"""
    __tablename__ = "goals"

    class Config:
        alias_generator = to_camel
        populate_by_name = True

    id: Optional[int] = Field(default=None, primary_key=True)
    session_id: int = Field(foreign_key="goal_setting_sessions.id")

    # Goal details
    title: str
    description: str
    category: str  # strategic, operational, tactical
    timeframe: Optional[str] = None

    # SMART criteria
    specific: str  # What exactly will be accomplished?
    measurable: str  # How will success be measured?
    achievable: str  # Is this realistic?
    relevant: str  # Why does this matter?
    time_bound: str  # When will this be achieved?

    # Success criteria
    success_criteria: Optional[List[str]] = Field(default=None, sa_column=Column(JSON))

    # Dependencies and risks
    dependencies: Optional[List[str]] = Field(default=None, sa_column=Column(JSON))
    risks: Optional[List[str]] = Field(default=None, sa_column=Column(JSON))

    # Priority and effort
    priority: str = Field(default="medium")  # high, medium, low
    estimated_effort: Optional[str] = None  # e.g., "2 sprints", "1 month"

    display_order: int = Field(default=0)
    created_at: datetime = Field(default_factory=datetime.utcnow)


# Pydantic models for API requests/responses
class GoalSettingSessionCreate(SQLModel):
    """Request model for creating a new session"""
    domain: str  # PM Role / Domain
    strategy: str  # Company Strategy
    team_charter: Optional[str] = None
    problem_statements: Optional[str] = None
    baselines: Optional[str] = None


class GoalSettingSessionResponse(SQLModel):
    """Response model for session data"""
    id: int
    domain: str
    strategy: str
    team_charter: Optional[str]
    problem_statements: Optional[str]
    baselines: Optional[str]
    status: str
    progress_message: Optional[str]
    error_message: Optional[str]
    executive_summary: Optional[str]
    created_at: datetime
    updated_at: datetime
    completed_at: Optional[datetime]

    class Config:
        alias_generator = to_camel
        populate_by_name = True


class GoalResponse(SQLModel):
    """Response model for goal data"""
    id: int
    session_id: int
    title: str
    description: str
    category: str
    timeframe: Optional[str]
    specific: str
    measurable: str
    achievable: str
    relevant: str
    time_bound: str
    success_criteria: Optional[List[str]]
    dependencies: Optional[List[str]]
    risks: Optional[List[str]]
    priority: str
    estimated_effort: Optional[str]
    display_order: int

    class Config:
        alias_generator = to_camel
        populate_by_name = True
