"""
Scope Monitor Models

Database models for monitoring scope changes and detecting scope creep.
"""
from datetime import datetime
from typing import Optional, List, Dict, Any
from sqlmodel import Field, SQLModel, JSON, Column
from humps import camelize


def to_camel(string):
    return camelize(string)


class ScopeMonitorSession(SQLModel, table=True):
    """Main session for scope monitoring"""
    __tablename__ = "scope_monitor_sessions"

    class Config:
        alias_generator = to_camel
        populate_by_name = True

    id: Optional[int] = Field(default=None, primary_key=True)
    user_id: Optional[int] = Field(default=None, foreign_key="users.id")

    # Input fields
    project_name: str
    baseline_scope_id: Optional[int] = Field(default=None, foreign_key="scope_definition_sessions.id")
    baseline_description: Optional[str] = None  # Manual baseline if no linked session
    current_requirements: str = Field(min_length=50)  # Current state of requirements
    change_context: Optional[str] = None  # Context about recent changes

    # Processing state
    status: str = Field(default="pending")  # pending, analyzing, completed, failed
    progress_message: Optional[str] = None
    error_message: Optional[str] = None

    # Analysis results
    scope_health_score: Optional[int] = None  # 0-100 score
    creep_risk_level: Optional[str] = None  # low, medium, high, critical
    executive_summary: Optional[str] = None
    recommendations: Optional[List[str]] = Field(default=None, sa_column=Column(JSON))

    # Metadata
    generation_metadata: Optional[Dict[str, Any]] = Field(default=None, sa_column=Column(JSON))
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    completed_at: Optional[datetime] = None


class ScopeChange(SQLModel, table=True):
    """Individual scope change detected"""
    __tablename__ = "scope_changes"

    class Config:
        alias_generator = to_camel
        populate_by_name = True

    id: Optional[int] = Field(default=None, primary_key=True)
    session_id: int = Field(foreign_key="scope_monitor_sessions.id")

    # Change details
    title: str
    description: str
    change_type: str  # addition, removal, modification, clarification
    category: str  # feature, requirement, constraint, timeline

    # Impact assessment
    impact_level: str  # low, medium, high, critical
    effort_impact: Optional[str] = None  # Estimated effort change
    timeline_impact: Optional[str] = None  # Estimated timeline change
    budget_impact: Optional[str] = None  # Estimated budget change

    # Classification
    is_scope_creep: bool = Field(default=False)
    creep_type: Optional[str] = None  # gold_plating, feature_creep, requirement_creep
    justification: Optional[str] = None  # Why this is/isn't scope creep

    # Recommendation
    recommendation: str  # accept, reject, defer, negotiate
    recommendation_rationale: Optional[str] = None

    display_order: int = Field(default=0)
    created_at: datetime = Field(default_factory=datetime.utcnow)


class ImpactAssessment(SQLModel, table=True):
    """Overall impact assessment for scope changes"""
    __tablename__ = "scope_impact_assessments"

    class Config:
        alias_generator = to_camel
        populate_by_name = True

    id: Optional[int] = Field(default=None, primary_key=True)
    session_id: int = Field(foreign_key="scope_monitor_sessions.id")

    # Assessment area
    area: str  # timeline, budget, resources, quality, risk

    # Impact details
    baseline_value: Optional[str] = None
    current_value: Optional[str] = None
    projected_value: Optional[str] = None

    impact_description: str
    impact_severity: str  # positive, neutral, minor_negative, major_negative, critical

    # Mitigation
    mitigation_options: Optional[List[str]] = Field(default=None, sa_column=Column(JSON))
    recommended_action: Optional[str] = None

    display_order: int = Field(default=0)
    created_at: datetime = Field(default_factory=datetime.utcnow)


class ScopeAlert(SQLModel, table=True):
    """Alert generated by scope monitoring"""
    __tablename__ = "scope_alerts"

    class Config:
        alias_generator = to_camel
        populate_by_name = True

    id: Optional[int] = Field(default=None, primary_key=True)
    session_id: int = Field(foreign_key="scope_monitor_sessions.id")

    # Alert details
    alert_type: str  # scope_creep, timeline_risk, budget_risk, resource_risk
    severity: str  # info, warning, critical
    title: str
    description: str

    # Related changes
    related_change_ids: Optional[List[int]] = Field(default=None, sa_column=Column(JSON))

    # Action items
    action_required: bool = Field(default=False)
    suggested_action: Optional[str] = None
    escalation_needed: bool = Field(default=False)

    # Status
    status: str = Field(default="active")  # active, acknowledged, resolved

    display_order: int = Field(default=0)
    created_at: datetime = Field(default_factory=datetime.utcnow)


# Pydantic models for API
class ScopeMonitorSessionCreate(SQLModel):
    """Request model for creating a new session"""
    project_name: str
    baseline_scope_id: Optional[int] = None
    baseline_description: Optional[str] = None
    current_requirements: str = Field(min_length=50)
    change_context: Optional[str] = None


class ScopeMonitorSessionResponse(SQLModel):
    """Response model for session data"""
    id: int
    project_name: str
    baseline_scope_id: Optional[int]
    baseline_description: Optional[str]
    current_requirements: str
    change_context: Optional[str]
    status: str
    progress_message: Optional[str]
    error_message: Optional[str]
    scope_health_score: Optional[int]
    creep_risk_level: Optional[str]
    executive_summary: Optional[str]
    recommendations: Optional[List[str]]
    created_at: datetime
    updated_at: datetime
    completed_at: Optional[datetime]

    class Config:
        alias_generator = to_camel
        populate_by_name = True


class ScopeChangeResponse(SQLModel):
    """Response model for scope change"""
    id: int
    session_id: int
    title: str
    description: str
    change_type: str
    category: str
    impact_level: str
    effort_impact: Optional[str]
    timeline_impact: Optional[str]
    budget_impact: Optional[str]
    is_scope_creep: bool
    creep_type: Optional[str]
    justification: Optional[str]
    recommendation: str
    recommendation_rationale: Optional[str]
    display_order: int

    class Config:
        alias_generator = to_camel
        populate_by_name = True


class ScopeAlertResponse(SQLModel):
    """Response model for scope alert"""
    id: int
    session_id: int
    alert_type: str
    severity: str
    title: str
    description: str
    related_change_ids: Optional[List[int]]
    action_required: bool
    suggested_action: Optional[str]
    escalation_needed: bool
    status: str
    display_order: int

    class Config:
        alias_generator = to_camel
        populate_by_name = True
